# Generated by Django 3.0.3 on 2022-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contribute',
            field=models.BooleanField(default=False),
        ),
    ]
