# Generated by Django 3.0.3 on 2022-07-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_contribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_contribute',
            field=models.BooleanField(default=False),
        ),
    ]
