# Generated by Django 3.0.3 on 2022-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signvideoupload',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signvideoupload',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
